// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUzkXM_EHdM4Ujj2DyO7I33rn-YfY9hyA',
    appId: '1:259055358038:web:edbd193e21fac710122bf7',
    messagingSenderId: '259055358038',
    projectId: 'london-5db92',
    authDomain: 'london-5db92.firebaseapp.com',
    storageBucket: 'london-5db92.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3_XxFMrIBSRrq60TG6C737w-rp0DGPOw',
    appId: '1:259055358038:ios:394c1e02ae5087f4122bf7',
    messagingSenderId: '259055358038',
    projectId: 'london-5db92',
    storageBucket: 'london-5db92.firebasestorage.app',
    iosBundleId: 'com.example.london',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3_XxFMrIBSRrq60TG6C737w-rp0DGPOw',
    appId: '1:259055358038:ios:394c1e02ae5087f4122bf7',
    messagingSenderId: '259055358038',
    projectId: 'london-5db92',
    storageBucket: 'london-5db92.firebasestorage.app',
    iosBundleId: 'com.example.london',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ncxx8UcwIYGnF06xTp4DliU883ocefY',
    appId: '1:259055358038:android:8807ab3cf54d047e122bf7',
    messagingSenderId: '259055358038',
    projectId: 'london-5db92',
    storageBucket: 'london-5db92.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUzkXM_EHdM4Ujj2DyO7I33rn-YfY9hyA',
    appId: '1:259055358038:web:8bca574252743d97122bf7',
    messagingSenderId: '259055358038',
    projectId: 'london-5db92',
    authDomain: 'london-5db92.firebaseapp.com',
    storageBucket: 'london-5db92.firebasestorage.app',
  );

}